### ISSUE TITLE
Does not connect with firebird 5.0.2

### ISSUE THREAD

**Issue by jlbeluco** [nakagami/pyfirebirdsql#115]
Report: I recently updated to the latest stable version of Firebird (5.0.2) and it doesn't connect and I don't receive a return message.

**Comment by 66zai** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。

**Comment by nakagami** [comment]
I have just released version 1.3.3.
Please try this latest version.

**Comment by jlbeluco** [comment]
Thank you very much for your promptness.
However, it still doesn't connect.

**Comment by nakagami** [comment]
Describe the traceback of the error.
Also, to the extent possible, please describe the code that causes the phenomenon.

**Comment by jlbeluco** [comment]
It is precisely at this point that I get lost.

It does not display any error message.

See part of the code. And, even simplifying the select, excluding the password, to avoid encryption and/or doing a generic select (without where), it always stops on the same line and does not display a return message ("my code is certainly not professional, I apologize for that.".

follows part of the code:
def AbreConexaoTeste():
    try:            
        if not sys.executable.endswith("app.exe"):
            connteste = firebirdsql.connect(
                user ="SYSDBA", 
                password="******", 
                database="C:\\xxx\\fb\\xxxxxxPY.FDB",
                host="localhost",
                charset="ISO8859_1")    
        else:
            connteste = firebirdsql.connect(
                user ="SYSDBA", 
                password="******", 
                database="C:\\xxx\\fb\\xxxxxx.FDB",
                host="localhost",
                charset="ISO8859_1")
        # conn.set_autocommit = False            

        return connteste
    except:
        flash('Atenção, falha ao Conecta ao banco de dados', 'error')
        return False            

=========================================================================
    ...
    if request.method == 'POST':
        cLogin = request.form['cLogin'].strip()
        cPword = (request.form['cPword'].strip()).upper()


        str2hash = cPword
        md5hash = hashlib.md5(str2hash.encode('utf-8')).hexdigest()

        cnx = AbreConexaoTeste()
        if cnx:
            if cnx.ping():
                cnxOK = 'S'
            else:
                cnx.close()
                flash('Falhou PING', 'error')
        else:
            flash('Falhou ao CRIAR conexão.', 'error')

        if cnxOK:
            with cnx:
                try:                    
                    try:
                        curx = cnx.cursor()
                        cnx.begin()
                    
                        query =  """select u.id, u.nome as nome_usu, u.senha, n.nome
                                    from tuser u join nomes n on u.id = n.id
                                    where ((u.dt_fim >= current_date) or (u.dt_fim is null))
                                    and (u.NOME = ?) and (U.SENHA = ?) """
**always stop here --->>>**        **curx.execute(query, (cLogin, md5hash))**                
                        tabAgtuser = curx.fetchall()
                        cnx.commit()
                    except:
                        cnx.rollback()
                        msg = f'Atenção, falha ao localizar Usuário - Login [{''} e {''}]'
                        flash(msg, 'error')
                    finally:
                        curx.close()
                except:
                    cnx.rollback()
                    flash('Falhou ao USAR a conexão.', 'error')
                finally:
                    cnx.close()
	...

Just for the record... this code has always worked fine with previous versions I've used (firebird 3.0, 4.0, 5.0 and 5.1)

**Comment by nakagami** [comment]
It looks like you are not doing anything special, just connecting and execute().
What is the content of Firebird.conf?
Do you have any particular unusual settings?

**Comment by nakagami** [comment]
Hmmm, I don't know why.
Is anyone else experiencing a similar phenomenon?

**Comment by nakagami** [comment]
@jibeluco
Is Port 3060 filtered or something?
Can you connect with isql command

**Comment by jlbeluco** [comment]
Looking more closely, debugging in VScode, I noticed that it is connecting. However, it does not execute the SQL.
See the code shown below.
It stops execution at the line "curx.execute(query, (cLogin, md5hash))" without any message.
This happens with Python 3.12.2 +Flask using VScode or Jupyter notebook.
However, it connects and executes SQL statements normally in ISQL, IBExpert, Software developed in Delphi 10.2 + Firedac.

Python code fragment:
...
    cnx = AbreConexaoTeste()
    if cnx:
        if cnx.ping():
            cnxOK = 'S'
        else:
            cnx.close()
            flash('Falhou PING', 'error')
    else:
        flash('Falhou ao CRIAR conexão.', 'error')

    if cnxOK:
        with cnx:
            try:                    
                try:
                    curx = cnx.cursor()
                    cnx.begin()
                
                    query =  """select u.id, u.nome as nome_usu, u.senha, n.nome
                                from tuser u join nomes n on u.id = n.id
                                where ((u.dt_fim >= current_date) or (u.dt_fim is null))
                                and (u.NOME = ?) and (U.SENHA = ?) """
		    **always stop here --->>> curx.execute(query, (cLogin, md5hash))**
...

**Comment by nakagami** [comment]
I have checked with Firebird 5.0.2 built from source and it seems to work in my environment (Ubuntu 24.04).

I think it's blocked somewhere here, but I can't figure out why.
https://github.com/nakagami/pyfirebirdsql/blob/master/firebirdsql/fbcore.py#L273-L284

**Comment by jlbeluco** [comment]
Hello,
I updated to 1.3.4 but the same symptom persists.
Following DEBUG line by line (attached is a text file describing the files and lines through which DEBUG navigated and a print of the last screen) until the last line, where it stopped (without a message being returned).
Would this help?

[fbcore_py DEBUG line by line.txt](https://github.com/user-attachments/files/19041294/fbcore_py.DEBUG.line.by.line.txt)
![Image](https://github.com/user-attachments/assets/dc003141-9ebe-4424-8ead-82471156a3ef)

**Comment by nakagami** [comment]
Hmmm, I don't know why.
Is it a Windows platform?

I do not have a Windows test environment.

I wonder if anyone else is experiencing the same phenomenon.

**Comment by jlbeluco** [comment]
Yes, Windows 11 24h2

**Comment by nakagami** [comment]
Thanks, this issue is helpful, but I will close this issue and fix it in #118.

**Comment by jlbeluco** [comment]
Hello,
Yes, it is now working fine with Python 3.12.2 + Firebird 5.0.2.
I have not tested it yet on Python 3.13.2 where the timezone no longer uses "resetlocale" and may give an error.
Thank you very much.
